<?php

namespace YapepBase\Autoloader;

require_once dirname(__FILE__) . '/../../Autoloader/AutoloaderBase.php';

/**
 * Test class for AutoloaderBase.
 * Generated by PHPUnit on 2011-12-14 at 10:49:39.
 */
class AutoloaderBaseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AutoloaderMock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \YapepBase\Test\Mock\Autoloader\AutoloaderMock();
    }

    public function testClassPath() {
        $this->object->setClassPath(array('/test1', '/test2'));
        $this->assertEquals(array('/test1', '/test2'), $this->object->getClassPath());
        $this->object->addClassPath('/test3');
        $this->assertEquals(array('/test1', '/test2', '/test3'), $this->object->getClassPath());
    }

    public function testRegister() {
        $this->object->register();
        AutoloaderRegistry::getInstance()->load('NonexitentImpossibleClass');
        $this->assertEquals(array('NonexitentImpossibleClass' => 'NonexitentImpossibleClass'), $this->object->loaded);
        $this->object->unregister();
        AutoloaderRegistry::getInstance()->load('NonexitentImpossibleClass2');
        $this->assertEquals(array('NonexitentImpossibleClass' => 'NonexitentImpossibleClass'), $this->object->loaded);
    }
}
