<?php

namespace YapepBase\Test\Util;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2012-01-31 at 12:10:44.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase {
    public function testOffset() {
        $collection = new \YapepBase\Test\Mock\Util\CollectionMock();
        $this->assertEquals(0, $collection->count());
        try {
            $collection->offsetGet(0);
            $this->fail('offsetGet on a non existent element in a Collection should result in an IndexOutOfBoundsException');
        } catch (\YapepBase\Exception\IndexOutOfBoundsException $e) { }
        $o = new \YapepBase\Test\Mock\Util\CollectionElementMock();
        $collection->offsetSet(0, $o);
        $this->assertEquals(1, $collection->count());
        $this->assertEquals($o, $collection->offsetGet(0));
        $this->assertEquals(true, $collection->offsetExists(0));
        $collection->offsetUnset(0);
        $this->assertEquals(0, $collection->count());
        try {
            $collection->offsetGet(0);
            $this->fail('offsetGet on a non existent element in a Collection should result in an IndexOutOfBoundsException');
        } catch (\YapepBase\Exception\IndexOutOfBoundsException $e) { }

        $collection->offsetSet(null, $o);
        $this->assertEquals(1, $collection->count());
        $this->assertEquals($o, $collection->offsetGet(1));
        $this->assertEquals(true, $collection->offsetExists(1));
        $collection->offsetUnset(1);
        $this->assertEquals(0, $collection->count());
        try {
            $collection->offsetGet(0);
            $this->fail('offsetGet on a non existent element in a Collection should result in an IndexOutOfBoundsException');
        } catch (\YapepBase\Exception\IndexOutOfBoundsException $e) { }

        try {
            $collection->offsetUnset(0);
            $this->fail('offsetUnset on a non existent element in a Collection should result in an IndexOutOfBoundsException');
        } catch (\YapepBase\Exception\IndexOutOfBoundsException $e) { }
    }
}
