<?php

namespace YapepBase\Tests\Util;

/**
 * Test class for CsvParser.
 * Generated by PHPUnit on 2012-02-23 at 11:49:26.
 */
class CsvParserTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var CsvParser
     */
    protected $object;

    public function setUp() {
        $this->object = new \YapepBase\Util\CsvParser();
    }

    public function testParseString() {
        for ($i=1; $i<3; $i++) {
            include(dirname(__FILE__) . '/../TestData/Util/CsvParser/testdata' . $i . '.php');
            $string = file_get_contents(dirname(__FILE__) . '/../TestData/Util/CsvParser/testdata' . $i . '.csv');
            $this->assertEquals($testdata, $this->object->parseString($string),
                'CsvParser parsed testdata' . $i . '.csv wrong');
        }
    }

    public function testParseStringWithHeaders() {
        include(dirname(__FILE__) . '/../TestData/Util/CsvParser/testdataheaders.php');
        $string = file_get_contents(dirname(__FILE__) . '/../TestData/Util/CsvParser/testdataheaders.csv');
        $this->assertEquals($testdata, $this->object->parseStringWithHeaders($string));
    }
}

