<?php

namespace YapepBase\Batch;

/**
 * Test class for LockingBatchScript.
 * Generated by PHPUnit on 2012-02-01 at 13:16:41.
 */
class LockingBatchScriptTest extends \YapepBase\BaseTest {

	public function testLock() {
		$this->markTestIncomplete('Locking batch script tests are not implemented yet');
	}
}
