<?php

namespace YapepBase\Syslog;

/**
 * Test class for SyslogConnection.
 * Generated by PHPUnit on 2011-12-06 at 11:33:00.
 */
class SyslogConnectionTest extends \YapepBase\BaseTest {
	/**
	 * @var \YapepBase\Mock\Syslog\SyslogConnectionMock
	 */
	protected $object;

	public function setUp() {
		parent::setUp();
		$this->object = new \YapepBase\Mock\Syslog\SyslogConnectionMock();
	}

	public function testExceptionConversion() {
		$this->object->setExceptions(true);
		$this->assertFalse($this->object->openlog('test', 0, Syslog::LOG_USER));
		$this->assertFalse($this->object->syslog(Syslog::LOG_NOTICE, 'test'));
		$this->assertFalse($this->object->closelog());
	}
}